package com.epam.xmlparsing.utils;

public enum TagName {
	
	MENU, MENUSECTION, MENUSIMPLEITEM, MENUCOMPLEXITEM, 
	MENUITEMPIC, MENUITEMNAME, MENUITEMDESCRIPTION, 
	MENUITEMPORTION, MENUITEMPRICE, MENUCOMPLEXITEMCHOICE,
	CHOICENAME, PRICE

}